HW1 is completed
pershin-daniil/Go-Professional-OTUS pull request #1
Opened 2023-05-23 17:08 UTC by pershin-daniil

## Домашнее задание №1 «Hello, OTUS!»

### Чек-лист студента
- [ ] Я перечитал задание после решения.
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл.
- [ ] Я использовал `stringutil.Reverse`.
- [ ] Я сравнил объем кода с объемом авторского решения.
  - main.go ~12 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Используется `stringutil` - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-06-01 03:09 UTC, dshemin requested changes

2023-06-01 03:09 UTC, dshemin commented on hw01_hello_otus/go.mod
> +module github.com/pershin-daniil/hw01_hello_otus
Критично:

Должно быть имя пользователя, название репозитория и название папки. Правильно так:

`github.com/pershin-daniil/Go-Professional-OTUShw01_hello_otus`

2023-06-01 15:48 UTC, pershin-daniil commented on hw01_hello_otus/go.mod
> +module github.com/pershin-daniil/hw01_hello_otus
@dshemin поправил

2023-06-02 19:17 UTC, dshemin approved these changes

2023-06-05 16:35 UTC, merged